/*
  create TABLE TRANSACTIONS
   (	"ID" NUMBER(19,0) NOT NULL ENABLE,
	"AMOUNT" FLOAT(126),
	"BALANCE" FLOAT(126),
	"CREATION_DATE" DATE,
	"ID_USER" NUMBER(19,0),
	 PRIMARY KEY ("ID")

   );
DROP TABLE IF EXISTS transactions;
*/

CREATE TABLE transactions (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  amount REAL NOT NULL,
  balance REAL NOT NULL,
  CREATION_DATE DATE,
  ID_USER INT
);